config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

	root 'static_pages#home'
	get 'static_pages/home'
	get  '/help', to: 'static_pages#help'
	get  '/about', to: 'static_pages#about'
	get  '/contact', to: 'static_pages#contact'
	get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
	get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
	resources :users
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	before_save { self.email = email.downcase }
	validates :name,  presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
	format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

	include SessionsHelper

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

	def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
    else
      flash[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
    @user = User.new(user_params)    # Not the final implementation!
    if @user.save
			flash[:success] = "Welcome to the Sample App!"
    	redirect_to @user
    else
      render 'new'
    end
  end

	private

	 def user_params
		 params.require(:user).permit(:name, :email, :password,
																	:password_confirmation)
	 end

end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	# Returns the Gravatar for the given user.
   def gravatar_for(user, options = { size: 80 })
     gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
     size = options[:size]
     gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
     image_tag(gravatar_url, alt: user.name, class: "gravatar")
   end

	 def show_users
		 @users.each do |u|
			 u.email
		 end
	 end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->
<html>
<head>
	<title><%=  link_to full_title(yield(:title)), root_path %></title>
	<%= csrf_meta_tags %>
	<%= stylesheet_link_tag    'application', media: 'all',
	'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<!--[if lt IE 9]>
	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->
</head>
<body>
	<header class="navbar navbar-fixed-top navbar-inverse">

		<div class="container">
			<%= link_to "sample app", '#', id: "logo" %>
			<nav>
				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to "Home",   root_path %></li>
					<li><%= link_to "Help",   help_path %></li>
					<li><%= link_to "About",   about_path %></li>
					li><%= link_to "Contact",   contact_path %></li>
					<li><%= link_to "Log in", login_path %></li>
				</ul>
			</nav>
		</div>
	</header>

	<br>
	<br><br>
	<div class="container">
		<% flash.each do |message_type, message| %>
		<%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
		<% end %>
	</div>

	<div class="container">
		<%= yield %>
	</div>

</body>

<%= debug(params) if Rails.env.development? %>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<%provide(:title, "About")%>
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
  </head>
  <body>
    <h1>About</h1>
    <p>
      The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
      Tutorial</em></a> is a
      <a href="http://www.railstutorial.org/book">book</a> and
      <a href="http://screencasts.railstutorial.org/">screencast series</a>
      to teach web development with
      <a href="http://rubyonrails.org/">Ruby on Rails</a>.
      This is the sample application for the tutorial.
    </p>
  </body>
</html>

app/views/static_pages/contact.html.erb
"Hello"
<% provide(:title, "Contact") %>
<title> <%= full_title(yield(:title)) %></title>

app/views/static_pages/help.html.erb
<%provide(:title, "Help")%>

<!DOCTYPE html>
<html>
  <head>
    <title><%=yield(:title)%> | Ruby on Rails Tutorial Sample App</title>
  </head>
  <body>
    <h1>Sample App</h1>
    <p>
      This is the home page for the
      <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
      sample application.
    </p>
  </body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
  </head>
  <body>
    <h1>Sample App</h1>
    <p>
      This is the home page for the
      <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
      sample application.
    </p>
  </body>
</html>

app/views/users/index.html.erb
<%= show_users %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

		<%= render 'shared/error_messages' %>

    <%= form_for(@user) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>